_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.11.7
        t:
            "1":
                - 2
                - 1
                - 3
                - 12
                - 45
                - 55
            "2":
                - 2
                - 1
                - 3
                - 12
                - 45
                - 55
            "3":
                - 13
                - 23
                - 55
                - 61
            "4": 3.11.7
            "5": 0.18.7
            "8":
                - 5
            "12": 0.18.7
            "13": darwin-arm64
